package agent

import (
	"fmt"
	"html"
	"strings"
	"sync"
)

// DescribeToolCall converts tool name and arguments into a concise, human-readable Indonesian description
func DescribeToolCall(name string, args map[string]interface{}) string {
	name = strings.TrimSpace(name)

	getString := func(key string) string {
		if args == nil {
			return ""
		}
		if v, ok := args[key]; ok && v != nil {
			return fmt.Sprintf("%v", v)
		}
		return ""
	}

	truncate := func(s string, maxLen int) string {
		s = strings.TrimSpace(s)
		if len(s) > maxLen {
			return s[:maxLen] + "..."
		}
		return s
	}

	switch strings.ToLower(name) {
	case "browser":
		action := strings.ToLower(getString("action"))
		if action == "" {
			action = "open"
		}
		urlStr := getString("url")
		switch action {
		case "open":
			if urlStr != "" {
				return fmt.Sprintf("Membuka web %s", truncate(urlStr, 40))
			}
			return "Membuka halaman web"
		case "click":
			if idx := getString("index"); idx != "" {
				return fmt.Sprintf("Klik elemen web (index %s)", idx)
			}
			if sel := getString("selector"); sel != "" {
				return fmt.Sprintf("Klik elemen %s", truncate(sel, 25))
			}
			return "Klik elemen web"
		case "type":
			txt := getString("text")
			return fmt.Sprintf("Mengisi form input: %q", truncate(txt, 25))
		case "screenshot":
			return "Mengambil screenshot halaman web"
		case "scroll":
			dir := getString("direction")
			if dir == "" {
				dir = "ke bawah"
			}
			return fmt.Sprintf("Scroll halaman %s", dir)
		case "eval_js":
			return "Eksekusi script JavaScript di web"
		default:
			return fmt.Sprintf("Browser: %s", action)
		}

	case "http_request":
		urlStr := getString("url")
		method := strings.ToUpper(getString("method"))
		if method == "" {
			method = "GET"
		}
		if urlStr != "" {
			return fmt.Sprintf("Request %s ke %s", method, truncate(urlStr, 35))
		}
		return "Mengirim HTTP request"

	case "g3a_describe_dataset":
		ds := getString("dataset")
		if ds != "" {
			return fmt.Sprintf("Inspeksi dataset %s", ds)
		}
		return "Inspeksi struktur dataset"

	case "g3a_query_analytics":
		ds := getString("dataset")
		if ds != "" {
			return fmt.Sprintf("Query analitik dataset %s", ds)
		}
		return "Query analitik data"

	case "g3a_run_sql":
		return "Eksekusi query SQL analitik"

	case "g3a_list_datasets":
		return "Memuat daftar dataset"

	case "g3a_export_chart_image":
		ds := getString("dataset")
		if ds != "" {
			return fmt.Sprintf("Menghasilkan grafik visual %s", ds)
		}
		return "Menghasilkan grafik visual"

	case "bash_exec":
		cmd := getString("command")
		if cmd != "" {
			return fmt.Sprintf("Eksekusi perintah: %s", truncate(cmd, 35))
		}
		return "Menjalankan perintah terminal"

	case "get_current_time":
		return "Mengecek waktu & tanggal sistem"

	case "tavily_search", "web_search":
		q := getString("query")
		if q != "" {
			return fmt.Sprintf("Mencari info web: %s", truncate(q, 30))
		}
		return "Mencari informasi di internet"

	case "send_file":
		fPath := getString("file_path")
		if fPath != "" {
			return fmt.Sprintf("Mengirim file: %s", truncate(fPath, 25))
		}
		return "Mengirimkan file lampiran"

	case "user_memory":
		action := getString("action")
		if action != "" {
			return fmt.Sprintf("Akses memori pengguna (%s)", action)
		}
		return "Mengakses memori pengguna"

	case "capture_visit_performance":
		m := getString("month")
		if m != "" {
			return fmt.Sprintf("Capture & analisa Visit Performance (%s)", m)
		}
		return "Capture & analisa dashboard Visit Performance"

	case "delegate_task":
		role := getString("role")
		tasks := getString("tasks")
		if tasks != "" {
			return "Delegasi tugas paralel ke sub-agen"
		}
		if role != "" {
			return fmt.Sprintf("Delegasi tugas ke sub-agen @%s", role)
		}
		return "Delegasi tugas ke sub-agen"

	default:
		return fmt.Sprintf("Menjalankan tool %s", name)
	}
}

// ProgressStepItem represents one step in the agent execution pipeline
type ProgressStepItem struct {
	Description string
	Success     bool
	Failed      bool
	ErrorMsg    string
}

// ProgressTracker maintains live execution steps, summary plan, and renders a dynamic checklist
type ProgressTracker struct {
	mu           sync.Mutex
	planText     string
	steps        []ProgressStepItem
	currentStep  string
	onProgressFn func(string)
}

// NewProgressTracker creates a new tracker instance with a callback
func NewProgressTracker(onProgress func(string)) *ProgressTracker {
	return &ProgressTracker{
		onProgressFn: onProgress,
	}
}

// SetPlan sets the preliminary plan generated by the LLM
func (p *ProgressTracker) SetPlan(plan string) {
	p.mu.Lock()
	p.planText = strings.TrimSpace(plan)
	p.mu.Unlock()
	p.Notify()
}

// StartStep marks a new step as currently running
func (p *ProgressTracker) StartStep(desc string) {
	p.mu.Lock()
	p.currentStep = desc
	p.mu.Unlock()
	p.Notify()
}

// CompleteStep records a step as completed (success or failure) and clears current active step
func (p *ProgressTracker) CompleteStep(desc string, err error) {
	p.mu.Lock()
	item := ProgressStepItem{
		Description: desc,
		Success:     err == nil,
		Failed:      err != nil,
	}
	if err != nil {
		item.ErrorMsg = err.Error()
	}
	p.steps = append(p.steps, item)
	p.currentStep = ""
	p.mu.Unlock()
	p.Notify()
}

// SetCurrent sets the current active action (e.g. analyzing data, synthesizing response)
func (p *ProgressTracker) SetCurrent(desc string) {
	p.mu.Lock()
	p.currentStep = desc
	p.mu.Unlock()
	p.Notify()
}

// Notify triggers the onProgress callback with the newly rendered HTML
func (p *ProgressTracker) Notify() {
	if p.onProgressFn == nil {
		return
	}
	rendered := p.Render()
	if rendered != "" {
		p.onProgressFn(rendered)
	}
}

// Render formats the plan and checklist into a clean, Telegram/WebAdmin compatible HTML string
func (p *ProgressTracker) Render() string {
	p.mu.Lock()
	defer p.mu.Unlock()

	var sb strings.Builder

	// 1. Render Summary Plan if present
	if p.planText != "" {
		cleanPlan := p.planText
		if len(cleanPlan) > 400 {
			cleanPlan = cleanPlan[:400] + "..."
		}
		sb.WriteString("🎯 <b>Rencana Pengerjaan:</b>\n")
		sb.WriteString(fmt.Sprintf("<blockquote expandable>%s</blockquote>\n\n", html.EscapeString(cleanPlan)))
	}

	// 2. Render Checklist Steps
	if len(p.steps) > 0 || p.currentStep != "" {
		sb.WriteString("📋 <b>Progres Pengerjaan:</b>\n")

		// Completed steps (limit to last 6 if many)
		displaySteps := p.steps
		if len(displaySteps) > 6 {
			displaySteps = displaySteps[len(displaySteps)-6:]
		}

		totalCount := len(p.steps)
		if p.currentStep != "" {
			totalCount++
		}

		for idx, st := range displaySteps {
			stepNum := idx + 1
			if st.Failed {
				errMsg := ""
				if st.ErrorMsg != "" {
					errMsg = fmt.Sprintf(" <i>(gagal: %s)</i>", html.EscapeString(st.ErrorMsg))
				}
				sb.WriteString(fmt.Sprintf("⚠️ [%d/%d] %s%s\n", stepNum, totalCount, html.EscapeString(st.Description), errMsg))
			} else {
				sb.WriteString(fmt.Sprintf("✅ [%d/%d] %s\n", stepNum, totalCount, html.EscapeString(st.Description)))
			}
		}

		// Current running step
		if p.currentStep != "" {
			curNum := len(p.steps) + 1
			cleanCur := strings.TrimRight(strings.TrimSpace(p.currentStep), ". ")
			sb.WriteString(fmt.Sprintf("⏳ [%d/%d] <i>%s...</i>\n", curNum, totalCount, html.EscapeString(cleanCur)))
		}
	} else if p.currentStep != "" {
		cleanCur := strings.TrimRight(strings.TrimSpace(p.currentStep), ". ")
		sb.WriteString(fmt.Sprintf("⏳ <i>%s...</i>", html.EscapeString(cleanCur)))
	}

	return strings.TrimSpace(sb.String())
}
